#
# Copyright 2025, Gerasim Troeglazov, 3dEyes@gmail.com. All rights reserved.
# Distributed under the terms of the MIT License.
#
# Build information summary output
#

message(STATUS "")
message(STATUS "Build Summary")
message(STATUS "=============")
message(STATUS "Version:        ${PROJECT_VERSION}")
message(STATUS "Build type:     ${CMAKE_BUILD_TYPE}")
message(STATUS "Install prefix: ${CMAKE_INSTALL_PREFIX}")
message(STATUS "")
message(STATUS "Tools to build:")
message(STATUS "  hvif2svg:     ${BUILD_HVIF2SVG}")
message(STATUS "  svg2hvif:     ${BUILD_SVG2HVIF}")
message(STATUS "  iom2svg:      ${BUILD_IOM2SVG}")
message(STATUS "  svg2iom:      ${BUILD_SVG2IOM}")
message(STATUS "  img2svg:      ${BUILD_IMG2SVG}")
message(STATUS "  msg2txt:      ${BUILD_MSG2TXT}")
if(HAIKU)
    message(STATUS "  iom2hvif:     ${BUILD_IOM2HVIF}")
endif()
if(WIN32)
    message(STATUS "  hvif4win:     ${BUILD_HVIF4WIN}")
endif()
message(STATUS "")
message(STATUS "Integration:")
message(STATUS "  Inkscape ext: ${BUILD_INKSCAPE_EXTENSIONS}")
message(STATUS "")
message(STATUS "Development options:")
message(STATUS "  Warnings:     ${HVIF_TOOLS_WARNINGS}")
message(STATUS "  Werror:       ${HVIF_TOOLS_WERROR}")
message(STATUS "  Tests:        ${HVIF_TOOLS_TESTS}")
message(STATUS "  Sanitizers:   ${HVIF_TOOLS_SANITIZERS}")
message(STATUS "")

set(_targets_list "")
if(TARGET hvif2svg)
    list(APPEND _targets_list "hvif2svg")
endif()
if(TARGET svg2hvif)
    list(APPEND _targets_list "svg2hvif")
endif()
if(TARGET iom2svg)
    list(APPEND _targets_list "iom2svg")
endif()
if(TARGET svg2iom)
    list(APPEND _targets_list "svg2iom")
endif()
if(TARGET img2svg)
    list(APPEND _targets_list "img2svg")
endif()
if(TARGET msg2txt)
    list(APPEND _targets_list "msg2txt")
endif()
if(TARGET iom2hvif)
    list(APPEND _targets_list "iom2hvif")
endif()
if(TARGET HVIFThumbnailProvider)
    list(APPEND _targets_list "HVIFThumbnailProvider")
endif()

list(LENGTH _targets_list _targets_count)

if(_targets_count GREATER 0)
    message(STATUS "Configured targets (${_targets_count}):")
    foreach(_target ${_targets_list})
        message(STATUS "  ${_target}")
    endforeach()
    message(STATUS "")
    
    message(STATUS "Build commands:")
    message(STATUS "  All targets:      cmake --build .")
    message(STATUS "  Specific target:  cmake --build . --target <name>")
    message(STATUS "")
    
    if(HVIF_TOOLS_INSTALL)
        message(STATUS "Installation:")
        message(STATUS "  cmake --install .")
        message(STATUS "")
    endif()
    
    message(STATUS "Packaging:")
    message(STATUS "  cmake --build . --target package")
    message(STATUS "")
else()
    message(WARNING "No targets configured! Enable at least one BUILD_* option.")
endif()
